node_specs:
  - name: src
    importance: 1
    icon: source
  - name: tests
    icon: test
  - extension: py
    importance: 1
  - name: dist
    importance: -1
    icon: share
nerd_icons:
  share: "\uf14d"
emoji_icons:
  share: "🎁"
