prefs:
  collapse: 1
node_specs:
  - name: src
    importance: 1
    icon: source
  - name: tests
    icon: test
  - extension: py
    importance: 1
  - name: dist
    importance: -1
    icon: share
nerd_icons:
  share: "\uf14d"
  link: "\uf838"
emoji_icons:
  share: "🎁"
  link: "🔗"
constants:
  node_types:
    symlink:
      icon: link
      color: bright_magenta
